# This workflow runs for new tags created only on the main branch
name: Deploy to Production
on:
  create

jobs:
  confirm-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        id: validate_tag
        run: |
          if [[ ! "${GITHUB_REF#refs/tags/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag does not match semver pattern. Exiting."
            exit 1
          fi

      - name: Validate branch
        id: check_main
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          MAIN_COMMIT=$(git rev-list -n 1 origin/main)
          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "Tag is not from the main branch. Exiting."
            exit 1
          fi

  build-and-upload:
    runs-on: ubuntu-latest
    needs: [confirm-tag]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build & deploy
        run: |
          echo vercel build
          echo vercel deploy --prebuilt --prod >deployment-url.txt 2>error.txt
      # Do we still need to alias? $deploymentUrl to dev.surfe.com 
      # Maybe not, Vercel might take care of this