# This workflow runs for any PR merged into main
name: Merge and deploy to Staging
on:
  pull_request:
    branches:
    - main
    types: [closed]

jobs:
  confirm-merge:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Confirm'
        run: echo Just checking PR is merged and not closed
  build:
    runs-on: ubuntu-latest
    needs: [confirm-merge]
    steps:
      - name: 'Confirm'
        run: echo Just checking