# This workflow runs anytime code is pushed to any branch, except for main

name: Lint code
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    # Ignore all branches except main
    branches:    
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #run: npm install --global vercel@latest
      - run: echo "I will lint things"
  deploy-preview:
    runs-on: ubuntu-latest
    needs: [lint-code]
    steps:  
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt 2>error.txt
          deploymentUrl=`cat deployment-url.txt`
          vercel alias $deploymentUrl trunkbased-cicd-workflow-staging.vercel.app --token=${{ secrets.VERCEL_TOKEN }}