# This workflow runs anytime code is pushed to any branch, except for main

name: Lint code
on:
  push:
    # Ignore all branches except main
    branches:    
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I will lint things"